export * from './api';
export * as cardService from './card.service';
export * as tutorService from './tutor.service';
export * as petService from './pet.service';
export * as vaccineService from './vaccine.service';
export * as dewormingService from './deworming.service';
export * as medicationService from './medication.service';
export * as uploadService from './upload.service';
export * as clinicService from './clinic.service';
export * as appointmentService from './appointment.service';
export * as calendarService from './calendar.service';
export * as deviceService from './device.service';
